version: '3.7'
services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
            args:
                uid: ${UID}
        image: 'laravelapp'
        container_name: laravel
        environment:
          - APACHE_RUN_USER=#${UID}
          - APACHE_RUN_GROUP=#${UID}
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - ./:/var/www/html
        user: devuser
        networks:
            - network
        depends_on:
            - mysql
            - redis
            - selenium
            - npm
    mysql:
        image: 'mysql:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - network
        healthcheck:
            test: ["CMD", "mysqladmin", "ping"]
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - network
        healthcheck:
                test: ["CMD", "redis-cli", "ping"]
    npm:
        image: node:14
        container_name: npm
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - network
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        volumes:
            - 'sailmeilisearch:/data.ms'
        networks:
            - network
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - network
    selenium:
        image: 'selenium/standalone-chrome'
        volumes:
            - '/dev/shm:/dev/shm'
        networks:
            - network
networks:
    network:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
    sailmeilisearch:
        driver: local